### ISSUE TITLE
Angular is not defined

### ISSUE THREAD

**Issue by bdougie** [imdoingotherthings/bloc-jams-angular#2]
when I open the app I see this picture, seems like Angular is broken.

<img width="1073" alt="screenshot 2016-11-11 18 10 41" src="https://cloud.githubusercontent.com/assets/5713670/20235010/d8d71dc0-a83b-11e6-9d63-2fd113fe5da8.png">

Any thoughts on what is happening?

**Comment by imdoingotherthings** [comment]
Yea its angular that is not defined anywhere. I'm looking through the code now to find the issue.

**Comment by bdougie** [comment]
Looks like upgrading Angular fixes the issues:

```
 <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js"></script>

```

**Comment by imdoingotherthings** [comment]
I'm receiving the same errors on my end...

![angular update to 1 5 8 - angular not defined while method chaining](https://cloud.githubusercontent.com/assets/20527548/20235481/b4d5427e-a847-11e6-8e70-e24dc109fc3a.png)

**Comment by bdougie** [comment]
Did you update to 1.5.8?

**Comment by bdougie** [comment]
You also have a few errors elswhere on master
1. You are not using [ui-sref](https://www.bloc.io/users/asai-andrade/checkpoints/2139?roadmap_section_id=186). It's referenced in Checkpoint 3. 
2. You have commas causing errrors in all your controllers. Open the console to check those out. https://github.com/imdoingotherthings/bloc-jams-angular/blob/master/app/scripts/controllers/AlbumCtrl.js#L7
