### ISSUE TITLE
Not retrieving music in album page and images for collection page not appearing 

### ISSUE THREAD

**Issue by imdoingotherthings** [imdoingotherthings/bloc-jams-angular#4]
For the collection page, no images for the albums are appearing which doesn't give me the option to navigate to album page to play music. 

After I manually navigate to the album page using `localhost:3000/album` I get an error when I click on the play button in one of the given song rows. 
Error reads: `GET http://localhost:3000/assets/music/blue.mp3 404 (Not Found) - blue.mp3:1`

This is the branch I was working on when I received the error.
[https://github.com/imdoingotherthings/bloc-jams-angular/tree/servicePt2](url)

![collection with error](https://cloud.githubusercontent.com/assets/20527548/20293117/5b1ba080-aaa8-11e6-8cb2-a9499aaf767d.png)

![album page with error](https://cloud.githubusercontent.com/assets/20527548/20293123/6d59e7de-aaa8-11e6-9cba-43d27deee526.png)

**Comment by bdougie** [comment]
If I console.log(this.albums) I get:

``` js
[undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined]
```

https://github.com/imdoingotherthings/bloc-jams-angular/blob/servicePt2/app/scripts/controllers/CollectionCtrl.js#L3

**Comment by bdougie** [comment]
You are [pushing](https://github.com/imdoingotherthings/bloc-jams-angular/blob/servicePt2/app/scripts/controllers/CollectionCtrl.js#L3) `undefined` to an array 12 times, this is the source of your error. You want to push the actual album instead.  

```
// line 40 of Fixtures.js

    for (var count = 0; count < numberOfAlbums; count++) {
      albumArray.push(count[numberOfAlbums]); // push the album here instead
    }
    return albumArray;

```

**Comment by imdoingotherthings** [comment]
I forgot to use console.log to check my code...man! 
But yes thank you. I see now that I hard coded 12 as a placeholder for the actual albums that I initially wrote in the Fixtures.getCollection function.
