### ISSUE TITLE
Having trouble accessing the albums.

### ISSUE THREAD

**Issue by imdoingotherthings** [imdoingotherthings/bloc-jams-angular#5]
Currently this is the code that is in my `player_bar.html` file. Here in this code I want to access the albums elements including the song name, the artist, and the duration of the song.
I understand that we went over how we were accessing these elements but my question is, where do I inject the code to access albums? Do I write another `div` and give it a `class` of `album.albumData` ?

```
<div class="control-group currently-playing" >
	    <h2 class="song-name">{{ album.albumData.song }}</h2>
	    <h2 class="artist-song-mobile"></h2>
	    <h3 class="artist-name">{{ album.artist }}</h3>
	<div class="seek-control">
	    <seek-bar></seek-bar>
	    <div class="current-time"></div>
            <div class="total-time">{{ song.duration}}</div>
	</div>
</div>
```

**Comment by bdougie** [comment]
You will need to add a [ng-controller](https://docs.angularjs.org/api/ng/directive/ngController) to the parent div. You also have two choices, 1 Create a PlayerbarCtrl and inject Fixtures or just add the AblumCtrl  to the div and do the same

**Comment by imdoingotherthings** [comment]
So I've tried using the `ng-controller` like so in the parent `div` : `ng-controller="AlbumCtrl"` but nothing is showing. I also thought that perhaps I was looking in the wrong function since at the moment my `AlbumCtrl.js` file is looking for `getAlbum` inside of `Fixtures` . So when we set `this.albumData = Fixtures.getAlbum` its only looking for `albumPicasso` since thats what we have it returning inside the function. 

I also tried `ng-controller="Fixtures.getCollection"` to look for the albums and still nothing.

**Comment by bdougie** [comment]
try `ng-controller="AlbumCtrl as album"`

Fixtures is not a controller, but actually a factory. That approach will not work, but good thought.

**Comment by imdoingotherthings** [comment]
I created a Player Bar controller, defined its url, templateUrl and its controller but my player bar still isn't updating to the artist name, duration of the song and the song title. 

My code: 
```
.state('playerBar', {
  url: '/playerBar',
  controller: 'PlayerBarCtrl as playerBar',
  templateUrl: '/templates/player_bar.html'
});
``` 
This code is in my `app.js` file and have used the controller in my `player_bar.html` like so: `ng-controller="PlayerBarCtrl as playerBar"`. Previously I have used it in my `<div class="control-group currently-playing">` but as I was looking through the checkpoint I saw that we had already included the controller in our `<section></section>` - https://github.com/imdoingotherthings/bloc-jams-angular/blob/master/app/templates/player_bar.html#L1 .

**Comment by bdougie** [comment]
Your player bar doesn't need a new state. This is only you have a playerBar page and want to display it on the https://localhost:3000/playerBar url. 

Aside, what branch are you working on? I still see some errors on master that were already fixed. [This](https://github.com/imdoingotherthings/bloc-jams-angular/blob/master/app/scripts/controllers/CollectionCtrl.js#L3) should not have `numberOfAlbums`. I trying to see your error locally but getting errors elsewhere.

It seems like an older commit overwrote your fixes. See how you are still calling [album.Title](https://github.com/imdoingotherthings/bloc-jams-angular/blob/master/app/templates/album.html#L7-L9)

https://github.com/imdoingotherthings/bloc-jams-angular/blob/master/app/templates/album.html#L7-L9

<img width="1162" alt="screenshot 2016-11-23 07 14 33" src="https://cloud.githubusercontent.com/assets/5713670/20563089/91b7830c-b14c-11e6-93f5-ace81e4b8f0d.png">

**Comment by bdougie** [comment]
This issue technically has already been resolved.
